version: '3.8'
services:
  prod-service:
    build:
      context: ./services/prod-service
    ports:
      - "3002:3002"
    container_name: prod-service

  users-service:
    container_name: users-service
    build:
      context: ./services/users-service
    environment:
      - MONGO_URI=${MONGO_URI}
    ports:
      - "3001:3001"
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - prod-service
      - users-service
