#values.yaml
replicaCount: 1

image:
  repository: ghcr.io/yakirovadya/frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 80

route:
  enabled: true
  tls:
    enabled: true
    termination: edge
