#values.yaml
replicaCount: 1

image:
  repository: ghcr.io/yakirovadya/frontend-new
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080
  targetPort: 8080

route:
  enabled: true
  tls:
    enabled: true
    termination: edge
