# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  selector:
    app: products-service
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.targetPort } }
  type: { { .Values.service.type } }
