# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: prod-service
  template:
    metadata:
      labels:
        app: prod-service
    spec:
      containers:
        - name: prod-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
