name: CI/CD Pipeline - Build and Deploy to OpenShift

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker image to GHCR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ secrets.REPO_NAME }}/products-service:latest ./products-service

      - name: Push Docker image
        run: docker push ghcr.io/${{ secrets.REPO_NAME }}/products-service:latest

  deploy:
    name: Deploy to OpenShift
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Log in to OpenShift
        run: |
          oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER }}

      - name: Switch to project
        run: oc project yakprog-dev

      - name: Apply deployment manifests
        run: oc apply -f openshift/
